version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka-network
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - kafka-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  hbase-master:
    image: harisekhon/hbase
    container_name: hbase-master
    networks:
      - kafka-network
    environment:
      HBASE_MANAGES_ZK: "false"
    ports:
      - "16010:16010"

  hbase-regionserver:
    image: harisekhon/hbase
    container_name: hbase-regionserver
    networks:
      - kafka-network
    environment:
      HBASE_MANAGES_ZK: "false"
    depends_on:
      - hbase-master

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    networks:
      - kafka-network
    environment:
      SPARK_MODE: "master"
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker
    networks:
      - kafka-network
    environment:
      SPARK_MODE: "worker"
      SPARK_MASTER: "spark://spark-master:7077"
    ports:
      - "8081:8081"
    depends_on:
      - spark-master

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    networks:
      - kafka-network
    environment:
      CLUSTER_NAME: test-cluster
      CORE_CONF_fs_defaultFS: hdfs://hadoop-namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    networks:
      - kafka-network
    environment:
      CORE_CONF_fs_defaultFS: hdfs://hadoop-namenode:9000
      DFS_DATANODE_ADDRESS: 0.0.0.0:9864
      DFS_DATANODE_HTTP_ADDRESS: 0.0.0.0:9866
    ports:
      - "9864:9864"
      - "9866:9866"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode

networks:
  kafka-network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
